# Generated by Django 3.2.9 on 2021-11-17 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mapa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('excel', models.FileField(upload_to='uploads/')),
                ('tipo_mapa', models.CharField(choices=[('1', 'Departamental'), ('2', 'Municipal')], max_length=1)),
            ],
        ),
    ]
