# Generated by Django 3.2.9 on 2021-11-17 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mapificador', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mapa',
            old_name='excel',
            new_name='archivo_de_excel',
        ),
    ]
