# Generated by Django 3.2.9 on 2021-11-30 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mapificador', '0003_rename_archivo_de_excel_mapa_excel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mapa',
            new_name='modeloMapa',
        ),
    ]
